package enums;

public enum Genre {
    A_GENERAL_WORKS,

    AC_Collections_Series,
    AC1_Collections_of_monographs, _essays,
    AC2_Scrapbooks,
    AE1_Encyclopedias,
    AG1_Dictionaries_and_other_general_reference_works,
    AI1_Indexes,
    AM1_Museums, _methods_and_techniques,
    AM2_Collectors_and_collecting,
    AN1_Newspapers,
    AP1_Humorous_periodicals,
    AP2_Juvenile_periodicals,
    AP3_Periodicals_for_women,
    AS1_Academies_and_learned_societies,
    AS2_International_learning_associations_congresses_conferences,
    AY_Yearbooks_Almanacs_Directories,
    AY1_Annuals,
    AY2_Almanacs,
    AY3_Directories,
    AZ_History_of_scholarship_and_learning,
    AZ1_Scholarship_and_learning_along_the_humanities,
    AZ2_Philosophy_and_theory_of_learning,
    AZ3_Evaluation_history,

    B_PHILOSOPHY_PSYCHOLOGY,

    B1_Philosophy_General,
    BC_Logic,
    BC1_History_of_Logic,
    BC2_General_works,
    BD_Speculative_philosophy,
    BD1_General_philosophical_works,
    BD2_Metaphysics,
    BD3_Epistemology_Theory_of_knowledge,
    BD4_Methodology,
    BD5_Ontology_Including_being_the_soul_life_death,
    BD6_Cosmology_Including_teleology_space_and_time_structure_of_matter_plurality_of_worlds,
    BF_Psychology,
    BF1_Psychoanalysis,
    BF2_Gestalt_psychology,
    BF3_Psychotropic_drugs_and_other_substances,
    BF4_Sensation_Aesthesiology,
    BF5_Consciousness_Cognition_Including_learning_attention_comprehension_memory_imagination_genius_intelligence_thought_and_thinking_psycholinguistics_mental_fatigue,
    BF6_Motivation,
    BF7_Affection_Feeling_Emotion,
    BF8_Will_Volition_Choice_Control,
    BF9_Applied_psychology,
    BF10_New_Thought_Menticulture,
    BF11_Comparative_psychology_Animal_and_human_psychology,
    BF12_Psychology_of_sex_Sexual_behavior,
    BF13_Differential_psychology_Individuality_Self,
    BF14_Personality,
    BF15_Genetic_psychology,
    BF16_Developmental_psychology_Including_infant_psychology_child_psychology_adolescence_adulthood,
    BF17_Class_psychology,
    BF18_Temperament_Character,
    BF19_Physiognomy_Phrenology,
    BF20_Graphology_Study_of_handwriting,

    BH1_Aesthetics,

    BJ_Ethics,
    BJ1_History_of,
    BJ2_Religious_ethics,
    BJ3_Evolutionary_and_genetic_ethics,
    BJ4_Positivist_ethics,
    BJ5_Socialist_ethics,
    BJ6_Communist_ethics,
    BJ7_Totalitarian_ethics,
    BJ8_Feminist_ethics,
    BJ9_Individual_ethics_Character_Virtue,
    BJ10_Ethics_of_social_groups_classes,
    BJ11_Social_usages_Etiquette,

    C_AUXILIARY_SCIENCES_OF_HISTORY,

    CB1_History_of_Civilization,
    CB2_Terrestrial_evidence_of_interplanetary_voyages,
    CB3_Forecasts_of_future_progress,
    CB4_Civilization_and_race,
    CB5_Geography_and_civilization,
    CB6_War_and_civilization,
    CB7_Water_and_civilization,

    CC_Archaeology_and_Antiques,
    CC1_Archaeology_Theory_Methods_Preservation,
    CC2_Forgeries_of_antiquities,
    CC3_Stone_heaps_cairns_of_unknown_purpose,
    CC4_Hill_figures,

    CD_Diplomacy,
    CD1_Diplomatics,
    CD2_Archives,
    CD3_History_and_statistics,
    CD4_Seals,
    CD5_Iconography,
    CE_Recording_Time,
    CE1_Technical_Chronology,
    CE2_Calendar,

    CJ_Numismatics,
    CJ1_Coins,
    CJ2_Tokens,
    CJ3_Medals_and_medallions,

    CN_Inscriptions,
    CN1_Epigraphy,
    CN2_Ancient_inscriptions,
    CN3_Medieval_inscriptions,
    CN4_Modern_inscriptions,

    CR_Heraldry,
    CR1_Crests_monograms_devices_badges_mottoes,
    CR2_Shields_and_supporters,

    CS_Genealogy,
    CS1_Genealogical_lists,
    CS2_Family_history_covering_more_than_one_country,

    //  CT_Biography
    CT1_Biography_as_an_art_or_literary_form,
    // CT2	History_of_biographical_literature_Lives_of_biographers,

    D_WHOLISTIC_AND_ALTERNATIVE_SCIENCES_PARANORMAL,

    //     DA_Approaches_to_solve_ages_old_problems
    DA1_Different_thinking,
    DA2_Math_problems_taking_centuries_to_solve,
    DA3_Ancient_spiritual_practices_applied_to_problems,

    //    DB_Best_practice_for_safety_management
    DB1_Safety_culture_as_a_holistic_phenomenon,
    DB2_Procedures_and_protocols,

    // DH_Handcrafted_apothecary_goods
    DH1_Traditional_craftsmanship_and_natural_ingredients,
    DH2_Herbal_botanical_organic_products,
    DH3_Ayurveda_science_of_a_long_and_healthy_life,

    //DE_Environmental_goodness
    DE1_Fundamental_interconnectedness_of_all_things,
    DE2_Natural_elements_as_ingredients,

    //    DP_Paranormal
    DP1_Evidence_of_unexplained_phenomena,
    DP2_Extrasensory_perception,
    DP3_Telekinesis,
    DP4_Faith_healing,
    DP5_Energy_fields,
    DP6_Parapsychology,
    DP7_Telepathy,
    DP8_Clairvoyance,
    DP9_Prizes_for_proofs,
    DP10_Witchcraft,
    DP11_Astrology,
    DP12_Oracles_Sibyls_Divinations,
    DP13_Seers_Prophets_Prophecies,

    //     DS_Holism_in_Science
    DS1_Systematic_sustained_rejection_to_funding,
    DS2_Interrelation_and_fundamental_principles_sharing,
    DS3_Holistic_approaches_in_microbiology,
    DS4_Quantum_physics_unexplained_results,

    // DR_Reductionistic_approach_to_science
    DR1_Epistemological_reductionism,
    DR2_Molecular_biology,
    DR3_Systems_biology,
    DR4_Ontological_reductionism,
    DR5_Methodological_reductionism,
    DR6_DR6_Platonic_reality_extension,
    DR7_Unreasonable_effectiveness_of_mathematics_in_nature,

    // E_ESOTERISM_faith_and_religion_transcendence_mystic_experience_and_internal_realizations_of_the_Divine

    // BL_Religion
    BL1_Philosophy_of_religion_Psychology_of_religion_Religion_in_relation_to_other_subjects,
    BL2_Sacred_books_General,
    BL3_Religions_of_the_world,
    BL4_Natural_theology_Theism_Polytheism_Dualism_Pantheism_Monotheism,
    BL5_The_soul,
    BL6_The_myth_Comparative_mythology,
    BL7_Religions_in_relation_to_one_another,
    BL8_Eschatology,
    BL9_Worship_Cultus,
    BL10_IndoEuropean_Aryan,
    BL11_UralAltaic,
    BL12_Classical_Etruscan_Greek_Roman,
    BL13_Germanic_and_Norse,
    BL14_Hinduism,
    BL15_Jainism,
    BL16_Zoroastrianism_Mazdeism_Parseeism,
    BL17_Yezidis,
    BL18_Aramean,
    BL19_Chaldean,
    BL20_Harranian_PseudoSabian,
    BL21_Moabite_Philistine,
    BL22_Pacific_Ocean_islands_Oceania,
    BL23_Arctic_regions,
    BL24_Rationalism,
    BM1_Judaism,

    //   BP_Islam_Bahai_Faith_Theosophy_etc.
    BP1_Islam,
    BP2_Bahai_Faith,

    //   BQ_Buddhism
    BQ1_Hinayana_Buddhism,
    BQ2_Mahayana_Buddhism,
    BQ3_Tibetan_Buddhism_Lamaism,
    BQ4_Bonpo_Sect,
    BQ5_Pure_Land_Buddhism,
    BQ6_Tantric_Buddhism,
    BQ7_Zen_Buddhism,
    BR1_Christianity,
    BS1_The_Bible,
    BT_Doctrinal_Theology,
    BT1_Doctrine_and_dogma,
    BT2_Divine_law_Moral_government,
    BT3_God_Trinity,
    BT4_Christology,
    BT5_Relics,
    BV1_Practical_Theology_Worship,
    BX1_Christian_Denominations,

    F1_HISTORY,

    // G_GEOGRAPHY_ANTHROPOLOGY_RECREATION
    G1_Geography_General,
    G2_Toponymy,
    G3_Historical_geography,
    G4_Aerial_geography,
    G5_History_of_discoveries_explorations_and_travel,
    G6_Atlases,
    G7_Tropics_Torrid_Zone,
    G8_Polar_regions_Frigid_Zone,
    G9_Globes,
    G10_Maps,
    G11_Universe_Solar_system,
    G12_Unlocalized_maps,
    GA_Mathematical_geography_Cartography,
    GA1_Cartography,
    GA2_Cadastral_mapping,
    GA3_Statistical_mapping,
    GB_Physical_geography,
    GB1_Geomorphology_Landforms_Terrain,
    GB2_Slopes,
    GB3_Coasts,
    GB4_Reefs,
    GB5_Islands,
    GB6_Mountains_Orography,
    GB7_Other_natural_landforms_Floodplains_caves_deserts_dunes,
    GB8_Hydrology_Water,
    GB9_Ground_and_surface_waters,
    GB10_Natural_disasters,
    GC1_Oceanography,
    GE1_Environmental_sciences,
    GF1_Human_ecology_Anthropogeography,
    GN2_Anthropology,
    GR1_Folklore,
    GR2_Mythical_places,
    GT1_Manners_and_customs,
    GV1_Recreation_Leisure_General,
    GV2_Outdoor_life_Outdoor_recreation,
    GV3_Physical_education_and_training,
    GV4_Sports,
    GV5_Games_and_amusements,
    GV6_Dancing,
    GV7_Circuses_spectacles_etc,

    //  H_SOCIAL SCIENCES

    H1_Social_sciences_General,
    HA1_Statistics_Events_registration_Statistical_data,
    HB1_Economic_theory_Demography,
    HC1_Economic_history_and_conditions,
    HD1_Industries_Land_use_Labor,
    HE1_Transportation_and_communications,
    HF1_Commerce,
    HG1_Finance_General,
    HG2_Liquidity,
    HG3_Money,
    HG4_Banking,
    HG5_Insurance_of_deposits_Deposit_insurance,
    HG6_Credit_Debt_Loans,
    HG7_Foreign_exchange_International_finance,
    HG8_Lotteries,
    HG9_Insurance,
    HJ1_Public_finance,
    HM1_Social_systems,
    HM2_Social_structure,
    HM3_Social_institutions,
    HQ1_The_Family_Marriage_Women,
    HS1_Societies_secret_benevolent_etc,
    HT1_Communities_Classes_Races,
    HV11_Social_pathology_General,
    HV2_Refugee_problems,
    HV3_Gay_men_Lesbians,
    HV4_Special_classes_By_occupation,
    HV5_Poor_in_cities_Slums,
    HV6_Degeneration,
    HV7_Alcoholism_Intemperance_Temperance_reform,
    HV8_Tobacco_habit,
    HV9_Drug_habits_Drug_abuse,
    HV10_Criminology,
    HX1_Socialism_Communism_Anarchism,

    //      J_POLITICAL_SCIENCE

    JA1_Political_science_General,
    JC1_Political_theory_The_state_Theories_of_the_state,
    JF1_Political_institutions_and_public_administration,
    JS1_Local_government_Municipal_government,
    JV1_Colonies_and_colonization_Emigration_and_immigration_International_migration,
    JZ1_International_relations,
    JZ2_Intergovernmental_organizations_IGOs,
    JZ3_Promotion_of_peace_Peaceful_change,
    JZ4_Non_military_coercion,
    JZ5_The_armed_conflict_War_and_order,
    JZ6_Neutrality_Non_participation_in_wars_Norms_of_neutrality,
    JZ7_Humanitarian_aspects_of_war,

    //     K_LAW

    K1_Law_in_general_Comparative_and_uniform_law_Jurisprudence,
    KB1_Religious_law_in_general_Comparative_religious_law,
    KC1_Law_by_country,
    KZ2_Law_of_nations,

    //    L_EDUCATION

    L1_Education_General,
    LA1_History_of_education,
    LB1_Theory_and_practice_of_education,
    LC1_Special_aspects_of_education,
    LD1_Individual_institutions_by_country,

    //    M_MUSIC

    M1_Instrumental_music,
    M2_Vocal_music,
    M3_Literature_on_music,
    M4_Instruction_and_study,

    //        N_FINE_ARTS

    N1_Visual_arts,
    N2_Architecture,
    N3_Sculpture,
    N4_Drawing_Design_Illustration,
    N5_Painting,
    N6_Print_media,
    N7_Decorative_arts,
    N8_Arts_study_Exhibitions_Art_centers,

    //        P_LANGUAGE_AND_LITERATURE

    P1_Philology_Linguistics_General,
    P2_Greek_literature,
    P3_Roman_literature,
    P4_Modern_languages_Celtic_languages,
    P5_Romance,
    P6_Germanic,
    P7_English,
    P8_Slavic_Baltic_Albanian,
    P9_Uralic_Basque,
    P10_Oriental_philology_and_literature,
    P11_IndoIranian_philology_and_literature,
    P12_Languages_of_Eastern_Asia_Africa_Oceania,
    P13_Hyperborean_Indian_and_artificial_languages,
    P14_Literature_General,
    P15_Literary_history,
    P16_Poetry,
    P17_The_monologue,
    P18_The_dialogue,
    P19_The_performing_arts_Show_business,
    P20_Drama,
    P21_Prose,
    P22_Prose_fiction,
    P23_Oratory_Elocution,
    P24_Journalism_The_periodical_press,
    P25_French_literature,
    P26_Italian_literature,
    P27_Spanish_literature,
    P28_Portuguese_literature,
    P29_English_literature,
    P30_American_literature,
    P31_German_literature,
    P32_Dutch_literature,
    P33_Afrikaans_literature,
    P34_Scandinavian_literature,
    P35_Old_Norse_literature_Old_Icelandic_and_Old_Norwegian,
    P36_Modern_Icelandic_literature,
    P37_Swedish_literature,
    P38_Fiction_and_juvenile_belles_lettres,

    //   Q_SCIENCE

    Q1_Science_General,
    Q2_Mathematics,
    Q3_Astronomy,
    Q4_Physics,
    Q5_Chemistry,
    Q6_Geology,
    Q7_Natural_history_General,
    Q8_Botany,
    Q9_Zoology,
    Q10_Human_anatomy,
    Q11_Microbiology,

    //    R_MEDICINE

    R1_Medicine_General,
    R2_Public_aspects_of_medicine,
    R3_Medical_geography_Climatology,
    R4_Forensic_medicine_Medical_jurisprudence_Legal_medicine,
    R5_Toxicology_Poisons,
    R6_Pathology,
    R7_Internal_medicine,
    R8_Surgery,
    R9_Ophthalmology,
    R10_Otorhinolaryngology,
    R11_Gynecology_and_obstetrics,
    R12_Pediatrics,
    R13_Dentistry,
    R14_Dermatology,
    R15_Therapeutics_Pharmacology,
    R16_Pharmacy_and_materia_medica,
    R17_Nursing,
    R18_Botanic_Thomsonian_and_eclectic_medicine,
    R19_Homeopathy,
    R20_Other_systems_of_medicine_Including_chiropractic_osteopathy_osteomagnetics_neuropathy_mental_healing_magnetotherapy_mesmerism_naturopathy_organomic_medicine_phrenology_radiesthesia,

    //       S_AGRICULTURE

    S1_Agriculture_General_Included_history_education_farm_economics_agricultural_chemicals_soil_science_machinery_and_farm_engineering,
    S2_Plant_culture,
    S3_Forestry,
    S4_Animal_culture,
    S5_Aquaculture_Fisheries_Angling,
    S6_Hunting_sports_Including_wild_animals_trade,

    //  T_TECHNOLOGY

    T1_Technology_General,
    T2_Engineering_General_Civil_engineering,
    T3_Hydraulic_engineering,
    T4_Environmental_technology_Sanitary_engineering,
    T5_Highway_engineering_Roads_and_pavements_Bridges,
    T6_Railroad_engineering_and_operation,
    T7_Building_construction,
    T8_Mechanical_engineering_and_machinery,
    T9_Electrical_engineering_Electronics_Nuclear_engineering,
    T10_Motor_vehicles_Aeronautics_Astronautics,
    T11_Mining_engineering_Metallurgy,
    T12_Chemical_technology,
    T13_Photography,
    T14_Manufactures,
    T15_Handicrafts_Arts_and_crafts,
    T16_Home_economics,

    // U_MILITARY

    U1_Military_science_General,
    U2_Armies_Organization_distribution_military_situation,
    U3_Military_administration,
    U4_Maintenance_and_transportation,
    U5_Infantry,
    U6_Cavalry_Armor,
    U7_Artillery,
    U8_Military_engineering,
    U9_Air_forces_Air_warfare,
    U10_Military_astronautics_Space_warfare_Space_surveillance,
    U11_Military_hygiene_and_sanitation_Care_of_sick_and_wounded,

    //  V_BIBLIOGRAPHY._LIBRARY_SCIENCE._INFORMATION_RESOURCES_(GENERAL)

    V1_Books_General_Writing_Paleography,
    V2_Book_industries_and_trade,
    V3_Libraries_Book_collecting,
    V4_General_bibliography,
    V5_Information_resources_General,
    V6_Information_in_specific_formats_or_media,
    V7_Motion_pictures_Video_recordings_Sound_recordings,
    V8_Government_information,
    FICTION,
    NON_FICTION,
    DRAMA,
    ANIME
}